### ISSUE TITLE
Safari 5.1.7 for Windows

### ISSUE THREAD

**Issue by BlackMagic** [philipwalton/solved-by-flexbox#45]
What workarounds exist for this broken browser? I use it to assess if my HTML/CSS will work on Apple devices. It ignores standard Flexbox, even Solved by Flexbox articles.

**Comment by KenPowers** [comment]
Your best bet is probably something like BrowserStack. $19 / month if all you plan on doing is desktop browser testing.

Safari for Windows was discontinued due to lack of popularity. The latest version of Safari is Safari 8, so the old 5.1.7 version would not be a good indicator of what your site would look like on Apple devices.

**Comment by BlackMagic** [comment]
Thanks for the advice. Now all I've got to worry about is IE 11 incompatibility.
