### ISSUE TITLE
issue with grid's gutter

### ISSUE THREAD

**Issue by stryju** [philipwalton/solved-by-flexbox#48]
any grid row container cannot be styled properly, as the negative top margin messes up the area taken by that element - just give the container a border or background

**Comment by stryju** [comment]
proposed solution:

remove the negative top margin, as the side margin doesn't seem to be affected with that issue

**Comment by philipwalton** [comment]
This is how almost all grid systems work, and the standard solution is to not style the grid elements themselves; rather, you nest other elements inside of them and style those.

**Comment by stryju** [comment]
the problem is that despite the nesting, the margin will "bleed outside" the container :cry:

**Comment by philipwalton** [comment]
I don't think that's true (or I'm misunderstanding what you're saying). Margin collapsing doesn't happen with flex items, so if you nest, margins will be positioned against the flex item's content box.

Can you put together a demo of what you're experiencing?

**Comment by stryju** [comment]
http://jsbin.com/cifipu/1/

**Comment by philipwalton** [comment]
This is happening because of [margin collapsing](https://developer.mozilla.org/en-US/docs/Web/CSS/margin_collapsing) on the `<li>` elements. It's a general CSS issue and is not specific to the Solved by Flexbox grid or with flexbox in general.

If you don't want this behavior, you'll have to prevent the margins from collapsing. There are a number of ways to do this, though the easiest is to apply `overflow: hidden` to the `.li` styles.

Here's an example: http://jsbin.com/rogugigoxa/1/

**Comment by stryju** [comment]
i'll just go and hide in a corner now :blush: 

thanks for the time taken to look into that!

**Comment by philipwalton** [comment]
No problem. I'm happy to help.
