### ISSUE TITLE
Flexbox grid flexCells modifier

### ISSUE THREAD

**Issue by ismay** [philipwalton/solved-by-flexbox#55]
I've been looking at the source of your flexbox grid (which is very cool btw.), and I was wondering what the intended use is of the `.Flex--flexCells` modifier. I couldn't find any hints on the solved by flexbox site, or in the source.

I'd say it's meant to make flex-cells into a flex container (since that's what `display: flex` does), but why do that?

**Comment by philipwalton** [comment]
It's to make all the cells inside a grid row `display: flex`. This is used to make the equal-height column demos actually look equal in height. Since the HTML structure of the demo is `.Grid > .Grid-cell > .Demo`, I needed to not only make `.Grid-cell` elements equal height, but `.Demo` elements as well. The solution was to make `.Grid-cell` elements `display: flex`.

**Comment by ismay** [comment]
Right, that makes sense. Was wondering whether it was something generalised, or just specific to your demo. But I think I can leave that out for my implementation then. Thanks!

**Comment by philipwalton** [comment]
Yeah, you can probably leave it out. Arguably it's something that should be handled by the individual cells and not the grid itself.
