### ISSUE TITLE
White space when minimizing width of the window.

### ISSUE THREAD

**Issue by MikeVaz** [philipwalton/solved-by-flexbox#69]
Every flexbox layout solution I've seen and tried myself so far had the same issue.

Imagine you minimize the width of the window to the point when content couldn't shrink anymore. In this case the expected behavior would be for content to push the width of container.

But inside a flexbox it is behaving differently. The container width is pushed and stops shrinking but the content is still shrinking further. Which creates a white space to the side of the content.

This behavior completely ruins the use of flexboxes for layouts for now. See attached images. It would be more visible when responsive break points are removed.

![flexbox-layout-issue1](https://cloud.githubusercontent.com/assets/4261252/10791669/6331a06e-7d57-11e5-9346-6fe711fa7289.png)
![flexbox-layout-issue2](https://cloud.githubusercontent.com/assets/4261252/10791670/65c41776-7d57-11e5-9f40-6a4122cd884d.png)

**Comment by philipwalton** [comment]
> This behavior completely ruins the use of flexboxes for layouts for now.

Seems like kind of an exaggeration.

And I don't think this issue is specific to flexbox. If I remove all flexbox declarations from the holy grail layout demo, you see the same problem.

The issue occurs if you have content on your site that's wider than the viewport, so the browser tries to make it visible for you. You could use `overflow-x: hidden` to remove the scroll bars, but then you couldn't see the content.

Flexbox actually enables a better default behavior here than `display: block` because flexbox introduces the concept of [`min-width: auto`](https://drafts.csswg.org/css-flexbox/#min-size-auto). Of course that doesn't apply here because the items are in the column direction, but you could add a container around `.HolyGrail` and see it working.

**Comment by MikeVaz** [comment]
You are too quick to close the issue. I would recommend to try your solution in real live scenarios as I did. Then you'll find it is not ideal and this issue might become a show stopper.

I can show you several more examples to prove my point.

![flexbox-layout-issue3](https://cloud.githubusercontent.com/assets/4261252/10860501/16bae812-7f37-11e5-8f86-f2c16273dac5.png)


In the above screenshot I put something inside the content area that should push its width. It could be an image or a table with data. As you can it is not usable this way. 

Code below:

```HTML
<table border="1">
    <tr>
        <td>test-test-test</td>
        <td>test-test-test</td>
        <td>test-test-test</td>
        <td>test-test-test</td>
        <td>test-test-test</td>
        <td>test-test-test</td>
        <td>test-test-test</td>
        <td>test-test-test</td>
        <td>test-test-test</td>
        <td>test-test-test</td>
        <td>test-test-test</td>
        <td>test-test-test</td>
        <td>test-test-test</td>
    </tr>
</table>
```

**Comment by philipwalton** [comment]
What you're describing is a bug that [I've documented elsewhere](https://github.com/philipwalton/flexbugs#1-minimum-content-sizing-of-flex-items-not-honored). You can also refer to [this Chromium issue](https://code.google.com/p/chromium/issues/detail?id=426898) about it. (And FWIW, your table example works as expected in Firefox.)

I closed the issue because Solved by Flexbox is a demo site. It's not intended to be a place for reporting bugs or complaints about how flexbox works. For that you can use the [www-style](https://lists.w3.org/Archives/Public/www-style/) mailing list.

**Comment by MikeVaz** [comment]
I understand. It looks like it is not something you are actively working on. I had spent some time playing with flexboxes a while back but couldn't find a production ready solution for layouts. I hoped somebody had a solution for that. 
Thanks for your reply. It gave me some clue that is might be an actual Chrome bug.
