### ISSUE TITLE
Holy Grail Layout not 100% correct

### ISSUE THREAD

**Issue by halt-hammerzeit** [philipwalton/solved-by-flexbox#79]
In Chrome, open the holy grail layout demo, go to `<body/>` style and add `border-bottom: 10px solid black;` there.
You'll see the black border on the bottom of the screen which is not correct because it should have been on the bottom of the document.
The reason is that `height: 100%` doesn't stretch even though the children's height is clearly bigger.

**Comment by philipwalton** [comment]
This is expected behavior to deal with cross-browser incompatibilities. You could use `min-height: 100%`, which would work in Chrome, but it wouldn't work in IE 10-11. Here's an article explaining all of this that will probably help you: http://philipwalton.com/articles/normalizing-cross-browser-flexbox-bugs/

**Comment by halt-hammerzeit** [comment]
oh, really, it works with `min-height`

```
    border-bottom: 10px solid black;
    min-height: 100%;
    height: auto;
```

but then it won't work in IE, yeah.

ok, thx.
