### ISSUE TITLE
the sticky footer example only works because you have html {height: 100%;}

### ISSUE THREAD

**Issue by rtack** [philipwalton/solved-by-flexbox#89]
having min-height: 100%; instead of min-height: 100vh; only works in current chrome because you set
html {
height: 100%;
}

This should be documented as requirement.

Site {
  display: flex;
  min-height: 100%;
  flex-direction: column;
}

**Comment by philipwalton** [comment]
This is just how percentage heights work in CSS in general. I don't want to document CSS quirks unrelated to flexbox, as that would probably be overdoing it, and it would distract from the intent of the site.

For example, you could make the same argument that the code with [`width` + `padding`](https://github.com/philipwalton/solved-by-flexbox/blob/0768b90714007819e599e5bf44560e61b72d8af6/assets/css/components/site.css#L22-L23) a few lines below only works because I'm using `box-sizing: border-box`, but again, I think documenting that fact would be distracting from the main point of the demos.

**Comment by rtack** [comment]
you use 100% instead of 100vh as you want to cater for an old safari version. But at the same time this makes your demo not work on current chrome. 
I believe that's not a great tradeoff. 100vh is preferable and would work fine in current chrome without needing the html height: 100% which is not desirable anyway.

**Comment by philipwalton** [comment]
> you use 100% instead of 100vh as you want to cater for an old safari version. But at the same time this makes your demo not work on current chrome. 

The demo works fine in Chrome.

> I believe that's not a great tradeoff. 100vh is preferable and would work fine in current chrome without needing the html height: 100% which is not desirable anyway.

Exactly, which is why the demo recommends using `100vh`. I'm not sure what you see as the problem here.

**Comment by rtack** [comment]
demo recommends 100vh but the linked source which points to https://github.com/philipwalton/solved-by-flexbox/blob/master/assets/css/components/site.css  uses 100% and that didn't work fine anymore.

**Comment by philipwalton** [comment]
It does work fine, as it's the CSS used on the site right now. Please make sure you're not doing something else that's causing an issue with your code.
